import * as fs from 'fs/promises';
import * as path from 'path';
import { UserPreferences } from './types';

/**
 * Manages the CLAUDE.md file that stores user preferences
 */
export class ClaudeFileManager {
  private filePath: string;

  constructor(filePath?: string) {
    this.filePath = filePath || path.join(process.cwd(), 'CLAUDE.md');
  }

  /**
   * Reads the current CLAUDE.md file
   */
  async read(): Promise<string> {
    try {
      return await fs.readFile(this.filePath, 'utf-8');
    } catch (error) {
      // File doesn't exist yet, return empty string
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return '';
      }
      throw error;
    }
  }

  /**
   * Updates the CLAUDE.md file with new preferences
   */
  async update(preferences: UserPreferences): Promise<void> {
    const content = this.generateContent(preferences);
    
    // Ensure directory exists
    const dir = path.dirname(this.filePath);
    await fs.mkdir(dir, { recursive: true });
    
    await fs.writeFile(this.filePath, content, 'utf-8');
  }

  /**
   * Merges new preferences with existing content
   */
  async merge(preferences: UserPreferences): Promise<void> {
    const existingContent = await this.read();
    const existingPreferences = this.parseContent(existingContent);
    
    // Merge preferences
    const merged: UserPreferences = {
      communicationStyle: preferences.communicationStyle || existingPreferences.communicationStyle,
      topicPreferences: this.mergeArrays(
        existingPreferences.topicPreferences || [],
        preferences.topicPreferences || []
      ),
      technicalLevel: preferences.technicalLevel || existingPreferences.technicalLevel,
      formatPreferences: preferences.formatPreferences || existingPreferences.formatPreferences,
      languageStyle: preferences.languageStyle || existingPreferences.languageStyle,
      otherInsights: this.mergeArrays(
        existingPreferences.otherInsights || [],
        preferences.otherInsights || []
      ),
    };
    
    await this.update(merged);
  }

  /**
   * Generates markdown content from preferences
   */
  private generateContent(preferences: UserPreferences): string {
    const sections: string[] = [];
    
    sections.push('# User Preferences and Style\n');
    sections.push('*This file is automatically generated and updated by claude-memory based on interactions.*\n');
    sections.push(`*Last updated: ${new Date().toISOString()}*\n`);
    
    if (preferences.communicationStyle) {
      sections.push('## Communication Style\n');
      sections.push(`${preferences.communicationStyle}\n`);
    }
    
    if (preferences.technicalLevel) {
      sections.push('## Technical Expertise Level\n');
      sections.push(`${preferences.technicalLevel}\n`);
    }
    
    if (preferences.formatPreferences) {
      sections.push('## Response Format Preferences\n');
      sections.push(`${preferences.formatPreferences}\n`);
    }
    
    if (preferences.languageStyle) {
      sections.push('## Language and Tone\n');
      sections.push(`${preferences.languageStyle}\n`);
    }
    
    if (preferences.topicPreferences && preferences.topicPreferences.length > 0) {
      sections.push('## Topic Preferences and Interests\n');
      preferences.topicPreferences.forEach(topic => {
        sections.push(`- ${topic}\n`);
      });
      sections.push('');
    }
    
    if (preferences.otherInsights && preferences.otherInsights.length > 0) {
      sections.push('## Additional Insights\n');
      preferences.otherInsights.forEach(insight => {
        sections.push(`- ${insight}\n`);
      });
      sections.push('');
    }
    
    return sections.join('\n');
  }

  /**
   * Parses existing CLAUDE.md content into preferences
   */
  private parseContent(content: string): UserPreferences {
    const preferences: UserPreferences = {
      topicPreferences: [],
      otherInsights: [],
    };
    
    if (!content) return preferences;
    
    const lines = content.split('\n');
    let currentSection = '';
    let currentContent: string[] = [];
    
    for (const line of lines) {
      if (line.startsWith('## Communication Style')) {
        this.saveSection(preferences, currentSection, currentContent);
        currentSection = 'communicationStyle';
        currentContent = [];
      } else if (line.startsWith('## Technical Expertise Level')) {
        this.saveSection(preferences, currentSection, currentContent);
        currentSection = 'technicalLevel';
        currentContent = [];
      } else if (line.startsWith('## Response Format Preferences')) {
        this.saveSection(preferences, currentSection, currentContent);
        currentSection = 'formatPreferences';
        currentContent = [];
      } else if (line.startsWith('## Language and Tone')) {
        this.saveSection(preferences, currentSection, currentContent);
        currentSection = 'languageStyle';
        currentContent = [];
      } else if (line.startsWith('## Topic Preferences')) {
        this.saveSection(preferences, currentSection, currentContent);
        currentSection = 'topicPreferences';
        currentContent = [];
      } else if (line.startsWith('## Additional Insights')) {
        this.saveSection(preferences, currentSection, currentContent);
        currentSection = 'otherInsights';
        currentContent = [];
      } else if (line.startsWith('#') || line.startsWith('*')) {
        // Skip headers and metadata
        continue;
      } else if (line.trim()) {
        currentContent.push(line);
      }
    }
    
    // Save the last section
    this.saveSection(preferences, currentSection, currentContent);
    
    return preferences;
  }

  private saveSection(preferences: UserPreferences, section: string, content: string[]) {
    if (!section || content.length === 0) return;
    
    const text = content.join('\n').trim();
    
    switch (section) {
      case 'communicationStyle':
        preferences.communicationStyle = text;
        break;
      case 'technicalLevel':
        preferences.technicalLevel = text;
        break;
      case 'formatPreferences':
        preferences.formatPreferences = text;
        break;
      case 'languageStyle':
        preferences.languageStyle = text;
        break;
      case 'topicPreferences':
        preferences.topicPreferences = content
          .map(line => line.replace(/^[-*]\s*/, '').trim())
          .filter(line => line.length > 0);
        break;
      case 'otherInsights':
        preferences.otherInsights = content
          .map(line => line.replace(/^[-*]\s*/, '').trim())
          .filter(line => line.length > 0);
        break;
    }
  }

  private mergeArrays(existing: string[], newItems: string[]): string[] {
    const merged = [...existing];
    for (const item of newItems) {
      if (!merged.includes(item)) {
        merged.push(item);
      }
    }
    return merged;
  }
}
